/* Generated by JavaFromJSON */
/*http://javafromjson.dashingrocket.com*/

package com.gm.ans;

import org.codehaus.jackson.annotate.JsonProperty;

public class Questions {
	@JsonProperty("qid")
	private java.lang.String qid;

 	public void setQid(java.lang.String qid) {
		this.qid = qid;
	}

	public java.lang.String getQid() {
		return qid;
	}

	@ JsonProperty("qtype")
	private java.lang.String qtype;

 	public void setQtype(java.lang.String qtype) {
		this.qtype = qtype;
	}

	public java.lang.String getQtype() {
		return qtype;
	}

	@JsonProperty("text")
	private java.lang.String text;

 	public void setText(java.lang.String text) {
		this.text = text;
	}

	public java.lang.String getText() {
		return text;
	}

	@ JsonProperty("input")
	private java.lang.String input;

 	public void setInput(java.lang.String input) {
		this.input = input;
	}

	public java.lang.String getInput() {
		return input;
	}

	@ JsonProperty("option")
	private java.lang.Object[] option;

 	public void setOption(java.lang.Object[] option) {
		this.option = option;
	}

	public java.lang.Object[] getOption() {
		return option;
	}

}