
/* Generated by JavaFromJSON */
/*http://javafromjson.dashingrocket.com*/

package com.gm.ans;

import org.codehaus.jackson.annotate.JsonProperty;

public class QuestionGroup  {
	@ JsonProperty("question")
	private Questions[] question;

 	public void setQuestion(Questions[] question) {
		this.question = question;
	}

	public Questions[] getQuestion() {
		return question;
	}

	@ JsonProperty("name")
	private java.lang.String name;

 	public void setName(java.lang.String name) {
		this.name = name;
	}

	public java.lang.String getName() {
		return name;
	}

}